import 'package:flutter/material.dart';
import 'package:organize_flutter_project/src/views/utils/contants.dart';

class DietChart extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: kWhiteColor,
      appBar: AppBar(
        elevation: 0,
        backgroundColor: kWhiteColor,
        leading: BackButton(color: kPurpleColor),
        title: Text('Diet Chart', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: kBlackColor)),
      ),
      body: SingleChildScrollView(
        child: Container(
          margin: EdgeInsets.symmetric(horizontal: 16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              SizedBox(height: 20),
              Text('Before Blood Donation', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: kPurpleColor)),
              SizedBox(height: 15),
              Text("First of all, try to relax. Being scared makes your body tense up and makes the whole thing take longer. In terms of food, before you give blood it's essential that your iron levels are high and that you're as hydrated as possible. Here's 5 foods to eat before you donate:", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('1. Water', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/water.jpg', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("This one really has nothing to do with iron levels, but it is by far the most important thing to eat (drink) before you donate blood. Being sufficiently hydrated makes the whole process easier and helps you to feel less lightheaded when it's over.", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('2. Lean Red Meat', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/meat.jpg', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("While it's true that red meat should be eaten in moderation, it's not a bad idea to eat a steak before you give blood. With 2.4 milligrams of iron per 100 grams of meat, you'll pass the hemoglobin test with flying colors. Just make sure it's not too fatty.", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('3. Lentils', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/lentils.png', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("Red meat not your thing? No problem. Lentils are absolutely packed with iron, along with tons of other important nutrients, making them one of the healthiest foods out there.", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('4. Spinach', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/spinach-leaves.jpg', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("Channel your inner Popeye and load up on spinach before you donate blood. It's super versatile — sauté it, add it to a green smoothie, or use it as a vitamin-packed base for your favorite salad — and also surprisingly hydrating. Win win.", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('5. Watermelon', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/watermelon.jfif', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("Do you have trouble just drinking plain water? Try eating a hydrating watermelon instead. If you're not into watermelon, strawberries are another ultra-hydrating fruit that are perfect for eating before you donate blood.", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 20),
              Text('After Blood Donation', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: kPurpleColor)),
              SizedBox(height: 15),
              Text("Congrats! You just made a difference in as many as three people's lives. Re-hydrate and treat yo'self for being a good person with these 5 foods: ", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('1. Juice', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/juice.jpg', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("Ditch the boring water for a sweeter, hydrating option. If you're not about added sugars, try coconut water or a cold-pressed juice.", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('2. Cookies', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/cookies.jpg', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("No nutritional value here, but hey — you deserve a treat. While the blood drive will likely provide these, you can also bake your own.", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('3. Avocado', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/avocados.jpg', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("Since you're supposed to avoid fatty foods before you donate, be sure to go ham on some avocados afterwards. On top of being delicious, they're packed full of omega-3's. Score! Whether you smash it on top of a piece of toast or turn it into guac, there's really no way to go wrong here.", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('4. Mocktails', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/mocktails.jpg', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("The Red Cross recommends avoiding alcohol for at least 24 hours after you donate blood. Don't get too down, though, because there are tons of fun mocktails you can drink. I guarantee you won't even miss the alcohol.", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
              Text('5. Cereal', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: kBlackColor)),
              SizedBox(height: 10),
              Image.asset('assets/images/cereal.jpg', width: MediaQuery.of(context).size.width-32, height: 210, fit: BoxFit.cover),
              SizedBox(height: 10),
              Text("Not only is cereal the trendiest food of 2017, but also it's often fortified with iron. Opt for a low-sugar variety like cheerios or chex if you're tryna be extra healthy (but let's be real, lucky charms = life).", style: TextStyle(letterSpacing: 0.4, fontSize: 13, color: kBlackColor)),
              SizedBox(height: 15),
            ],
          ),
        ),
      ),
    );
  }
}
